{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b4ca53e7-d9e2-4530-ad3f-5e9266e29a8d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import coursierapi._\n",
    "interp.repositories() ++= Seq(MavenRepository.of(\"https://jitpack.io\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "85a49b11-7bb7-4527-b747-415ca011f382",
   "metadata": {},
   "outputs": [],
   "source": [
    "import $ivy.`com.github.dzufferey::scadla:0.1.1`\n",
    "import scadla._\n",
    "import InlineOps._\n",
    "import EverythingIsIn.{millimeters, degrees}\n",
    "import scadla.utils.thread.ISO\n",
    "import scadla.utils.CenteredCube\n",
    "import squants.space.{Length, Millimeters}\n",
    "import scala.language.postfixOps\n",
    "import squants.space.LengthConversions._\n",
    "import scadla.backends.OpenSCAD // for rendering (getting a mesh)\n",
    "import scadla.backends.almond.Viewer // to show the mesh in jupyter/almond"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d17a5db8-b09b-414a-849f-5e1cca063ec8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import $ivy.`com.github.dzufferey::libgcode:0.1-SNAPSHOT`\n",
    "import libgcode.utils.{Viewer => NcViewer, _}\n",
    "import libgcode._\n",
    "import libgcode.extractor._\n",
    "import libgcode.generator._\n",
    "import libgcode.utils.geometry2D._\n",
    "import scala.collection.mutable.ArrayBuffer"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b39170b1-8fb8-404d-94a0-abe10301b046",
   "metadata": {},
   "source": [
    "# Code For Structure"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e51db71b-1b80-4561-8d45-1b6afe9b7b7d",
   "metadata": {},
   "source": [
    "## Features (Holes, Slots, etc)\n",
    "\n",
    "Things that get removed from the base shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "746f51d7-9548-43c9-909d-4413ac3cbc4b",
   "metadata": {},
   "outputs": [],
   "source": [
    "//this a SubtractiveFeature which gives a model and toolpath\n",
    "//TODO generalize to multiple plane\n",
    "abstract class SubtractiveFeature {\n",
    "    def model(z: Length): Solid\n",
    "    def toolpath(z: Length)(implicit conf: Config): Seq[Command]\n",
    "}\n",
    "\n",
    "case class HoleSpec(\n",
    "    x: Length,\n",
    "    y: Length,\n",
    "    radius: Length,\n",
    "    depth: Length,\n",
    "    counterBore: Boolean = false,\n",
    "    threaded: Boolean = false\n",
    ") extends SubtractiveFeature {\n",
    "    \n",
    "    protected def counterBoreRadius = if (counterBore) 2*radius.to(Millimeters) else 0\n",
    "    protected def counterBoreDepth = if (counterBore) radius.to(Millimeters) else 0\n",
    "    protected def _x = x.to(Millimeters)\n",
    "    protected def _y = y.to(Millimeters)\n",
    "    protected def _radius = radius.to(Millimeters)\n",
    "    protected def _depth = depth.to(Millimeters)\n",
    "    \n",
    "    def model(z: Length) = {\n",
    "        val m0 = Cylinder(radius, depth)\n",
    "        val m1 = Cylinder(counterBoreRadius, counterBoreDepth).moveZ(depth - counterBoreDepth)\n",
    "        val m2 = m0 + m1\n",
    "        m2.move(x, y, z - depth)\n",
    "    }\n",
    "    \n",
    "    def spot(z: Length, ignoreCounterBore: Boolean)(implicit conf: Config): Seq[Command] = {\n",
    "        val _z = z.to(Millimeters)\n",
    "        if (ignoreCounterBore) {\n",
    "            Drill(_x, _y, _z, conf.endmillRadius)\n",
    "        } else {\n",
    "            Drill(_x, _y, _z - counterBoreDepth, conf.endmillRadius)\n",
    "        }\n",
    "    }\n",
    "    \n",
    "    def drill(z: Length, ignoreCounterBore: Boolean = false)(implicit conf: Config): Seq[Command] = {\n",
    "        val _z = z.to(Millimeters)\n",
    "        if (ignoreCounterBore) {\n",
    "            Drill(_x, _y, _z, _depth)\n",
    "        } else {\n",
    "            Drill(_x, _y, _z - counterBoreDepth, _depth - counterBoreDepth)\n",
    "        }\n",
    "    }\n",
    "    \n",
    "    protected def threadingHole(radius: Length) = {\n",
    "        implicit val tolerance = (1e-6 mm)\n",
    "        if (radius ~= ISO.M1_6) 1.25 / 2\n",
    "        else if (radius ~= ISO.M2) 0.8\n",
    "        else if (radius ~= ISO.M2_5) 1\n",
    "        else if (radius ~= ISO.M3) 1.25\n",
    "        else if (radius ~= ISO.M4) 1.6\n",
    "        else if (radius ~= ISO.M5) 2.1\n",
    "        else if (radius ~= ISO.M6) 2.5\n",
    "        else if (radius ~= ISO.M8) 3.4\n",
    "        else if (radius ~= ISO.M10) 4.25\n",
    "        else if (radius ~= ISO.M12) 5\n",
    "        else radius.to(Millimeters) * 0.4\n",
    "    }\n",
    "    \n",
    "    def toolpath(z: Length, ignoreShaft: Boolean)(implicit conf: Config): Seq[Command] = {\n",
    "        val _z = z.to(Millimeters)\n",
    "        val buffer = scala.collection.mutable.ArrayBuffer.empty[Command]\n",
    "        if (counterBore) {\n",
    "            buffer ++= Hole(_x, _y, _z, counterBoreRadius, counterBoreDepth)\n",
    "        }\n",
    "        if (!ignoreShaft) {\n",
    "            var r = if (threaded) threadingHole(radius) else _radius\n",
    "            buffer ++= Hole(_x, _y, _z - counterBoreDepth, r, _depth - counterBoreDepth)\n",
    "        }\n",
    "        buffer.toSeq\n",
    "    }\n",
    "    \n",
    "    def toolpath(z: Length)(implicit conf: Config): Seq[Command] = {\n",
    "        toolpath(z, false)\n",
    "    }\n",
    "}\n",
    "\n",
    "case class SlotSpec(\n",
    "    x1: Length, y1: Length,\n",
    "    x2: Length, y2: Length,\n",
    "    radius: Length, depth: Length\n",
    ") extends SubtractiveFeature {\n",
    "    protected def _x1 = x1.to(Millimeters)\n",
    "    protected def _y1 = y1.to(Millimeters)\n",
    "    protected def _x2 = x2.to(Millimeters)\n",
    "    protected def _y2 = y2.to(Millimeters)\n",
    "    protected def _radius = radius.to(Millimeters)\n",
    "    protected def _depth = depth.to(Millimeters)\n",
    "    \n",
    "    def model(z: Length): Solid = {\n",
    "        val _z = z.to(Millimeters)\n",
    "        val c = Cylinder(_radius,_depth)\n",
    "        Hull( c.move(_x1,_y1,_z), c.move(_x2,_y2,_z) )\n",
    "    }\n",
    "    \n",
    "    def toolpath(z: Length)(implicit conf: Config): Seq[Command] = {\n",
    "        val _z = z.to(Millimeters)\n",
    "        Slot(_x1, _y1, _z, _x2, _y2, _z, _radius, _depth)\n",
    "    }\n",
    "}\n",
    "\n",
    "case class PocketSpec(\n",
    "    x: Length, y: Length, // lower left corner\n",
    "    width: Length, length: Length, depth: Length\n",
    ") extends SubtractiveFeature {\n",
    "    protected def _x = x.to(Millimeters)\n",
    "    protected def _y = y.to(Millimeters)\n",
    "    protected def _width = width.to(Millimeters)\n",
    "    protected def _length = length.to(Millimeters)\n",
    "    protected def _depth = depth.to(Millimeters)\n",
    "    \n",
    "    def model(z: Length): Solid = {\n",
    "        Cube(width, length, depth).move(x, y, z-depth)\n",
    "    }\n",
    "    \n",
    "    def toolpath(z: Length)(implicit conf: Config): Seq[Command] = {\n",
    "        val _z = z.to(Millimeters)\n",
    "        Rectangle(_x, _y, _z, _width, _length, _depth)\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5411652a-2497-4fd5-aa9c-11e014350a49",
   "metadata": {},
   "source": [
    "## Parts\n",
    "\n",
    "A base 2D shape with features that gets removed"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1c5c148f-b121-4a3c-9821-0835a591300c",
   "metadata": {},
   "outputs": [],
   "source": [
    "object Side extends Enumeration {\n",
    "  type Side = Value\n",
    "  val Top, Bottom, Left, Right, Front, Back = Value\n",
    "}\n",
    "\n",
    "abstract class Part {\n",
    "    def model: Solid\n",
    "    def info: String\n",
    "    def contour(slotWidth: Length, onionSkin: Length = (0.5 mm))(implicit conf: Config): Seq[Command]\n",
    "    def chamfer(implicit conf: Config): Seq[Command]\n",
    "    def spotHoles(ignoreCounterBore: Boolean = false, side: Side.Side = Side.Top)(implicit conf: Config): Seq[Command]\n",
    "    def drillHoles(ignoreCounterBore: Boolean = false, side: Side.Side = Side.Top)(implicit conf: Config): Seq[Command]\n",
    "    def boreHoles(ignoreShaft: Boolean = false, side: Side.Side = Side.Top)(implicit conf: Config): Seq[Command]\n",
    "    def featureToolpath(implicit conf: Config): Seq[Command]\n",
    "    //TODO print hole info (side, position, diam, depth, threaded)\n",
    "}\n",
    "\n",
    "// a part defined by a contour, some holes, and other features where everything is machines from the top\n",
    "abstract class FlatPart(name: String) extends Part {\n",
    "    \n",
    "    // Bounding box for the model\n",
    "    def width: Length /* X */\n",
    "    def depth: Length /* Y */\n",
    "    def height: Length /* Z */\n",
    "\n",
    "    protected def _width = width.to(Millimeters)\n",
    "    protected def _depth = depth.to(Millimeters)\n",
    "    protected def _height = height.to(Millimeters)\n",
    "\n",
    "    def holes: Seq[(Side.Side,HoleSpec)]\n",
    "    def otherFeatures: Seq[SubtractiveFeature] = Seq()\n",
    "    \n",
    "    def baseModel: Solid\n",
    "    def baseShape: Path\n",
    "\n",
    "    def model: Solid = {\n",
    "        val hs = holes.map{ case (side, hole) =>\n",
    "            val m = hole.model(0)\n",
    "            side match {\n",
    "                case Side.Top => m.moveZ(height)\n",
    "                case Side.Bottom => m.rotateY(180).moveX(width)\n",
    "                case Side.Left => m.rotateY(-90)\n",
    "                case Side.Right => m.rotateY(90).move(width, 0, height)\n",
    "                case Side.Front => m.rotateX(90)\n",
    "                case Side.Back => m.rotateX(-90).move(0, depth, height)\n",
    "            }\n",
    "        }\n",
    "        val other = otherFeatures.map( _.model(height) )\n",
    "        baseModel -- hs -- other\n",
    "    }\n",
    "    \n",
    "    protected def contourLayer(slotWidth: Length)(implicit conf: Config): Path = {\n",
    "        val base = baseShape\n",
    "        val sw = slotWidth.to(Millimeters)\n",
    "        val inner = conf.finishingPass + conf.endmillRadius\n",
    "        val outer = sw - conf.endmillRadius\n",
    "        val (nSteps, stepSize) = evenSteps(inner, outer, conf.widthOfCut, conf.roundingError)\n",
    "        val offsets = (0 until nSteps).map( i => inner + i * stepSize )\n",
    "        val paths = offsets.map( o => base.offset(-o) ).toSeq\n",
    "        paths.reduceLeft((p0, p1) => {\n",
    "            val (a,b) = p0(1.0)\n",
    "            val (c,d) = p1(0.0)\n",
    "            val l = Line(a,b,c,d)\n",
    "            Path(p0.children ++ Seq(l) ++ p1.children)\n",
    "        })\n",
    "    }\n",
    "    \n",
    "    def contour(slotWidth: Length, onionSkin: Length)(implicit conf: Config): Seq[Command] = {\n",
    "        val layer = contourLayer(slotWidth)\n",
    "        val (a,b) = layer(0.0)\n",
    "        val layerCode = layer.toGCode(conf)\n",
    "        val (nSteps, stepSize) = evenSteps(_height, onionSkin.to(Millimeters), conf.depthOfCut, conf.roundingError)\n",
    "        val buffer = scala.collection.mutable.ArrayBuffer.empty[Command]\n",
    "        // to start\n",
    "        buffer += G(0, conf.x(a), conf.y(b))\n",
    "        buffer += G(1, conf.z(_height + conf.travelHeight), F(conf.plungeFeed))\n",
    "        buffer += Empty(F(conf.feed))\n",
    "        // layers\n",
    "        assert(nSteps > 0)\n",
    "        for (i <- 0 until nSteps - 1) {\n",
    "            buffer ++= layerCode\n",
    "            buffer += G(1, conf.x(a), conf.y(b), conf.z(_height + i * stepSize), F(conf.plungeFeed))\n",
    "            buffer += Empty(F(conf.feed))\n",
    "        }\n",
    "        if (conf.finishingPass > 0.0) {\n",
    "            val path = baseShape.offset(-conf.endmillRadius)\n",
    "            buffer ++= path.toGCode(conf)\n",
    "        }\n",
    "        // to rest\n",
    "        buffer += G(1, conf.x(a), conf.y(b))\n",
    "        buffer += G(1, conf.z(_height + conf.travelHeight), F(conf.plungeFeed))\n",
    "        buffer += Empty(F(conf.feed))\n",
    "        buffer.toSeq\n",
    "    }\n",
    "    \n",
    "    def chamfer(implicit conf: Config): Seq[Command] = {\n",
    "        val r = conf.endmillRadius\n",
    "        val delta = 0.1\n",
    "        val path0 = baseShape.offset(-delta)\n",
    "        val path = if (!conf.climb) path0 else path0.flip\n",
    "        val (a,b) = path(0)\n",
    "        val c = _height - r + delta\n",
    "        val buffer = scala.collection.mutable.ArrayBuffer.empty[Command]\n",
    "        buffer += G(0, conf.x(a), conf.y(b))\n",
    "        buffer += G(1, conf.z(c), F(conf.plungeFeed))\n",
    "        buffer += Empty(F(conf.feed))\n",
    "        buffer ++= path.toGCode(conf)\n",
    "        buffer += G(1, conf.z(_height + conf.travelHeight), F(conf.plungeFeed))\n",
    "        buffer += Empty(F(conf.feed))\n",
    "        buffer.toSeq\n",
    "    }\n",
    "        \n",
    "    def spotHoles(ignoreCounterBore: Boolean, side: Side.Side)(implicit conf: Config): Seq[Command] = side match {\n",
    "        case Side.Top => holes.flatMap{\n",
    "            case (Side.Top, h) => h.spot(height, ignoreCounterBore)\n",
    "            case (_, _) => Seq()\n",
    "        }\n",
    "        case _ => ???\n",
    "    }\n",
    "    \n",
    "    def drillHoles(ignoreCounterBore: Boolean, side: Side.Side)(implicit conf: Config): Seq[Command] = side match {\n",
    "        case Side.Top => holes.flatMap{\n",
    "            case (Side.Top, h) => h.drill(height, ignoreCounterBore)\n",
    "            case (_, _) => Seq()\n",
    "        }\n",
    "        case _ => ???\n",
    "    }\n",
    "    \n",
    "    def boreHoles(ignoreShaft: Boolean, side: Side.Side)(implicit conf: Config): Seq[Command] = side match {\n",
    "        case Side.Top => holes.flatMap{\n",
    "            case (Side.Top, h) => h.toolpath(height, ignoreShaft)\n",
    "            case (_, _) => Seq()\n",
    "        }\n",
    "        case _ => ???\n",
    "    }\n",
    "    \n",
    "    def featureToolpath(implicit conf: Config): Seq[Command] = {\n",
    "        otherFeatures.flatMap( _.toolpath(height) )\n",
    "    }\n",
    "    \n",
    "    def extraInfo: String = \"\"\n",
    "    \n",
    "    def info = {\n",
    "        val s = s\"\"\"|$name:\n",
    "                    |  width = $width\n",
    "                    |  depth = $depth\n",
    "                    |  height = $height\"\"\".stripMargin\n",
    "        val e = extraInfo\n",
    "        if (e.length > 0) s + \"\\n\" + e else s\n",
    "    }\n",
    "    \n",
    "}\n",
    "\n",
    "// a simple part is milled from one part with just a rectangle with some holes\n",
    "abstract class SimplePart(name: String) extends FlatPart(name) {\n",
    "    \n",
    "    def baseModel: Solid = {\n",
    "        Cube(width, depth, height)\n",
    "    }\n",
    "    \n",
    "    def baseShape: Path = {\n",
    "        val segments = IndexedSeq(\n",
    "            Line(0, 0, _width, 0),\n",
    "            Line(_width, 0, _width, _depth),\n",
    "            Line(_width, _depth, 0, _depth),\n",
    "            Line(0, _depth, 0, 0)\n",
    "        )\n",
    "        Path(segments)\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f2ddbb9f-d997-436b-962a-63598b2ec527",
   "metadata": {},
   "source": [
    "## Assemblies\n",
    "\n",
    "Put a bunch of parts together"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ff2f859a-5242-433e-80e3-a44fc4e48a61",
   "metadata": {},
   "outputs": [],
   "source": [
    "sealed abstract class Structure {\n",
    "    def model: Solid\n",
    "    def parts: Seq[Part]\n",
    "    def info: String\n",
    "}\n",
    "\n",
    "case class SinglePart(part: Part, transform: Solid => Solid = (s: Solid) => s) extends Structure {\n",
    "    def model = transform(part.model)\n",
    "    def parts = Seq(part)\n",
    "    def info = part.info\n",
    "}\n",
    "\n",
    "case class Placeholder(dummy: Solid, description: String) extends Structure {\n",
    "    def model = dummy\n",
    "    def parts = Seq[Part]()\n",
    "    def info = description\n",
    "}\n",
    "\n",
    "case class Composite(_parts: Seq[(Structure, Seq[Solid => Solid])]) extends Structure {\n",
    "    def model = Union(_parts.flatMap{ case (p, ts) => ts.map( t => t(p.model) ) }: _*)\n",
    "    def parts = _parts.flatMap{ case (p, _) => p.parts }\n",
    "    def info = _parts.map{ case (p, ts) => s\"(${ts.size}x) \" + p.info }.reduce(_ + \"\\n\" + _)\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ba3cc5c7-f44e-48ee-b456-f74bf2643c10",
   "metadata": {},
   "source": [
    "# New Z-axis for my cnc"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1f633855-a020-43c9-b361-46fc89fc1363",
   "metadata": {},
   "source": [
    "## Dimensions for mechanical components"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ad54d150-ad85-4422-b775-b554d30add37",
   "metadata": {},
   "outputs": [],
   "source": [
    "// linear rails (MGN 15C)\n",
    "object LinearRail {\n",
    "    val totalHeight = 16 mm // surface to surface distance includes rail + guide\n",
    "    val width = 15 mm\n",
    "    val height = 10 mm\n",
    "    val holesDistance = 40 mm\n",
    "    val holesRadius = ISO.M3\n",
    "    def screwPositions(length: Length) = { // x coord of the mounting screw\n",
    "        val n = ((length - holesRadius * 2) / holesDistance).floor.toInt\n",
    "        val offset = (length - holesDistance * n) / 2\n",
    "        (0 until n).map( i => offset + holesDistance * i)\n",
    "    }\n",
    "    // extend in x direction [0, length], y centered at 0, back against xy plane\n",
    "    def rail(length: Length) = {\n",
    "        val r = Cube(length, width, height).moveY(- width / 2)\n",
    "        val screw = Cylinder(holesRadius, height) + Cylinder(holesRadius * 2, holesRadius).moveZ(height - holesRadius + 0.1)\n",
    "        val hs = screwPositions(length).map( x => screw.moveX(x) )\n",
    "        r -- hs\n",
    "    }\n",
    "    def placeholder(l: Length) = {\n",
    "        new Placeholder(rail(l), s\"Linear Rail ($l)\")\n",
    "    }\n",
    "}\n",
    "object LinearGuide {\n",
    "    val length = 42.1 mm\n",
    "    val width = 32 mm\n",
    "    val height = 12 mm\n",
    "    val holesLength = 20 mm\n",
    "    val holesWidth = 25 mm\n",
    "    val holesRadius = ISO.M3\n",
    "    // centered at (0,0), back at 0 and guide facing up\n",
    "    val holePattern = Seq(( holesLength / 2,  holesWidth / 2),\n",
    "                          (-holesLength / 2,  holesWidth / 2),\n",
    "                          ( holesLength / 2, -holesWidth / 2),\n",
    "                          (-holesLength / 2, -holesWidth / 2))\n",
    "    val model = {\n",
    "        val c0 = CenteredCube.xy(length, width, height)\n",
    "        val c1 = c0 - CenteredCube.xy(length, LinearRail.width, LinearRail.height).moveZ(4)\n",
    "        c1 -- holePattern.map{ case (x,y) => Cylinder(holesRadius, height).move(x, y, 0) } // make througholes to see align\n",
    "    }\n",
    "    def placeholder = {\n",
    "        new Placeholder(model, \"LinearGuide\")\n",
    "    }\n",
    "}\n",
    "// ballscrew\n",
    "object BallScrew {\n",
    "    // https://www.dold-mechatronik.de/Spindelmuttergehaeuse-DSG1605-fuer-Kugelumlaufspindel-SFU1605-SFU1610\n",
    "    val nutHeight = 40 mm\n",
    "    val nutWidth = 52 mm\n",
    "    val nutLength = 40 mm\n",
    "    val nutHoles = ISO.M5\n",
    "    val nutHolesDistanceWidth = 40 mm\n",
    "    val nutHolesDistanceLength = 24 mm\n",
    "    val nutHolesPattern = Seq(( nutHolesDistanceLength / 2,  nutHolesDistanceWidth / 2),\n",
    "                              (-nutHolesDistanceLength / 2,  nutHolesDistanceWidth / 2),\n",
    "                              ( nutHolesDistanceLength / 2, -nutHolesDistanceWidth / 2),\n",
    "                              (-nutHolesDistanceLength / 2, -nutHolesDistanceWidth / 2))\n",
    "    // https://www.dold-mechatronik.de/Festlagereinheit-FLB20-3200-Easy-Mechatronics-System-1620B\n",
    "    val endHeight = 51 mm\n",
    "    val endWidth = 70 mm\n",
    "    val endDepth = 20 mm\n",
    "    val endHolesDistance = 55 mm\n",
    "    val endHoles = ISO.M6\n",
    "    val endHolesPattern = Seq(-endHolesDistance / 2, endHolesDistance / 2)\n",
    "    val bottomToRotationAxis = 31 mm\n",
    "    val bearingUnit = {\n",
    "        val c0 = CenteredCube.xy(endDepth, 40, endHeight)\n",
    "        val c1 = c0 + CenteredCube.xy(endDepth, endWidth, 10)\n",
    "        val c2 = c1 -- endHolesPattern.map( y => Cylinder(endHoles, 11).moveY(y) )\n",
    "        c2\n",
    "    }\n",
    "    // length is the distance between mounting screw\n",
    "    def model(l: Length) = {\n",
    "        bearingUnit + bearingUnit.moveX(l) + Cylinder(10, l).rotateY(90).moveZ(bottomToRotationAxis)\n",
    "    }\n",
    "    def placeholder(l: Length) = {\n",
    "        new Placeholder(model(l), s\"Ball Screw ($l)\")\n",
    "    }\n",
    "}\n",
    "// spindle clamp: https://www.dold-mechatronik.de/Eurohalsaufnahme-65x75x20\n",
    "object SpindleClamp {\n",
    "    val width = 65 mm\n",
    "    val height = 20 mm\n",
    "    val depth = 75 mm\n",
    "    val backToCenter = 42 mm\n",
    "    val centerDiameter = 43 mm\n",
    "    val centerGap = 2 mm\n",
    "    val mountingHoles = ISO.M8\n",
    "    val holesPosition = Seq(7.5 mm, 32.5 mm, 57.5 mm)\n",
    "    val holesHeight = 10 mm\n",
    "    val model = {\n",
    "        val x0 = Cube(width, depth, height)\n",
    "        val x1 = x0 - Cylinder(centerDiameter/2, height).move(width/2, backToCenter, 0)\n",
    "        val x2 = x1 - CenteredCube.x(centerGap, depth, height).move(width/2, backToCenter + 1, 0)\n",
    "        val screw = Cylinder(mountingHoles, 17).rotateX(-90)\n",
    "        val x3 = x2 -- holesPosition.map( x => screw.move(x, 0, height / 2) )\n",
    "        x3\n",
    "    }\n",
    "    def placeholder = {\n",
    "        new Placeholder(model, \"Spindle Clamp\")\n",
    "    }\n",
    "}\n",
    "\n",
    "def holesPosition0(n: Int, start: Length, end: Length) = {\n",
    "    val delta = (end - start) / (n-1)\n",
    "    (0 until n).map( i => start + delta * i )\n",
    "}\n",
    "\n",
    "def holesPosition1(n: Int, length: Length, distanceToBorder: Length) = {\n",
    "    holesPosition0(n, distanceToBorder, length - distanceToBorder)\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6a5574b2-c138-4cd1-a2d2-92d8cd805668",
   "metadata": {},
   "source": [
    "## XY table (already made)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c9bff178-36d7-43a9-8baf-0660a716a7c9",
   "metadata": {},
   "outputs": [],
   "source": [
    "object Table extends {\n",
    "    val mountingHolesWidth = 160 mm\n",
    "    val mountingHolesDepth = 80 mm\n",
    "    val mountingHoles = ISO.M8\n",
    "    val xTravel = 300 mm\n",
    "    val yTravel = 200 mm\n",
    "    val distBetweenPlates = BallScrew.nutHeight / 2 +  BallScrew.bottomToRotationAxis\n",
    "    val plateThickness = 20 mm\n",
    "    val totalHeigth = plateThickness * 3 + distBetweenPlates * 2\n",
    "    def model(x: Double = 0.5, y: Double = 0.5) = {\n",
    "        val lower = CenteredCube.xy(550, 200, plateThickness)\n",
    "        val mz = plateThickness + distBetweenPlates\n",
    "        val xPos = xTravel * (0.5 - x)\n",
    "        val middle = CenteredCube.x(200, 350, plateThickness).move(xPos, -130, mz)\n",
    "        val uz = mz * 2\n",
    "        val yPos = yTravel * (1 - y)\n",
    "        val upper = CenteredCube.xy(300, 200, plateThickness).move(xPos, yPos - 55, uz)\n",
    "        lower + middle + upper\n",
    "    }\n",
    "    val xOffset = 0 mm\n",
    "    val yOffset = 45 mm\n",
    "    def placeholder = {\n",
    "        new Placeholder(model(), \"Existing XY Table\")\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2fabb911-9113-4a50-8b81-056d87bb0641",
   "metadata": {},
   "outputs": [],
   "source": [
    "val mesh = OpenSCAD(Table.model())\n",
    "Viewer(mesh)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f791d414-4461-42d9-b9a4-6cf339db8510",
   "metadata": {},
   "source": [
    "## Draft"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "455dcb9d-8a0d-4469-95cc-cabde9283faa",
   "metadata": {},
   "outputs": [],
   "source": [
    "val carriageHeight = 150 mm\n",
    "val pillarInnerspace = BallScrew.nutWidth.max(BallScrew.endWidth) + 10 //TODO smaller endwidth\n",
    "val expectedTravel = 150 mm\n",
    "\n",
    "//TODO where to put the z-axis stop\n",
    "\n",
    "object Pillar extends FlatPart(\"Pillar\") {\n",
    "    \n",
    "    val kneeWidth = 50 mm\n",
    "    val kneeDepth = 20 mm\n",
    "    val pillarWidth = 60 mm\n",
    "    \n",
    "    def width = pillarWidth + kneeWidth\n",
    "    def depth = Table.totalHeigth +\n",
    "                 15 /* slots for t-nuts */ +\n",
    "                 30 + /* spindle collet to collar */\n",
    "                 carriageHeight + /* carriage heigth */\n",
    "                 expectedTravel /* expected z travel */\n",
    "    def height = 15 mm\n",
    "    \n",
    "    //TODO rail length should be somewhat standard\n",
    "    def railLength = depth\n",
    "    \n",
    "    val baseHoles = ISO.M8\n",
    "    val baseHolesNumber = 3\n",
    "    val baseHolesPositions = {\n",
    "        val toBorder = baseHoles * 2.5\n",
    "        val dist = (width - toBorder * 2) / (baseHolesNumber - 1)\n",
    "        Seq(toBorder, toBorder + dist - 5, toBorder + dist * 2)\n",
    "    }\n",
    "    \n",
    "    val frontThickness = 10 mm\n",
    "    val frontHole = ISO.M4\n",
    "    val frontDepth = depth - kneeDepth\n",
    "    val frontHolesPositions = holesPosition1(6, frontDepth, frontHole * 3 + 10).map( _ + kneeDepth )\n",
    "    \n",
    "    def holes = {\n",
    "        // (1) the base\n",
    "        val b = baseHolesPositions.map( x => (Side.Front, HoleSpec(x, height / 2, baseHoles, 15, threaded = true) ) )\n",
    "        // (2) the front\n",
    "        val f = frontHolesPositions.map( y => (Side.Top, HoleSpec(pillarWidth - frontThickness / 2, y, frontHole, kneeWidth + height, threaded = true) ) )\n",
    "        // (3) the rails\n",
    "        val r = LinearRail.screwPositions(railLength).map( y => (Side.Top, HoleSpec(pillarWidth/2, y, LinearRail.holesRadius, height, threaded = true)) )\n",
    "        b ++ f ++ r\n",
    "    }\n",
    "    \n",
    "    def baseModel = {\n",
    "        val p = Cube(pillarWidth, depth, height)\n",
    "        val k = Cube(pillarWidth + kneeWidth, kneeDepth, height)\n",
    "        p + k\n",
    "    }\n",
    "    \n",
    "    def baseShape = {\n",
    "        val points = IndexedSeq[(Length,Length)](\n",
    "            (0, 0),\n",
    "            (0, width),\n",
    "            (kneeDepth, width),\n",
    "            (kneeDepth, pillarWidth),\n",
    "            (depth, pillarWidth),\n",
    "            (depth, 0),\n",
    "            (0, 0)\n",
    "        )\n",
    "        val lines = points.sliding(2).map( s => Line(s(0)._1.to(Millimeters),\n",
    "                                                     s(0)._2.to(Millimeters),\n",
    "                                                     s(1)._1.to(Millimeters),\n",
    "                                                     s(1)._2.to(Millimeters)) )\n",
    "        Path(lines.toIndexedSeq)\n",
    "    }\n",
    "    \n",
    "    override def extraInfo = s\"  rail length =  $railLength\"\n",
    "\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "52b18bca-0787-4d0c-a80e-ab489f1bce4c",
   "metadata": {},
   "outputs": [],
   "source": [
    "val mesh = OpenSCAD(Pillar.model)\n",
    "Viewer(mesh)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ea1d6378-fac8-4f5e-917e-41d9a1dab5c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "object FrontPlate extends SimplePart(\"Front Plate\") {\n",
    "    \n",
    "    val width = pillarInnerspace\n",
    "    val depth = Pillar.frontDepth\n",
    "    val height = Pillar.frontThickness\n",
    "    \n",
    "    val ballScrewLength = expectedTravel + 200 // when I make a lower table, I'll have more travel\n",
    "    \n",
    "    def holes = {\n",
    "        // holes for pillar\n",
    "        val sideHoles = Pillar.frontHolesPositions.map( y => HoleSpec(height / 2, y, Pillar.frontHole, 10, threaded = true) )\n",
    "        val left = sideHoles.map( h => (Side.Left, h) )\n",
    "        val right = sideHoles.map( h => (Side.Right, h) )\n",
    "        // holes for ballscrew\n",
    "        def hBS(x: Length, y: Length) = (Side.Top, HoleSpec(x, y, BallScrew.endHoles, height, threaded = true))\n",
    "        val h2 = depth - 10\n",
    "        val h3 = h2 - ballScrewLength\n",
    "        val top = BallScrew.endHolesPattern.map( x => hBS(width/2+x, h2))\n",
    "        val bot = BallScrew.endHolesPattern.map( x => hBS(width/2+x, h3))\n",
    "        left ++ right ++ top ++ bot\n",
    "    }\n",
    "    \n",
    "    override def extraInfo = s\"  ballScrewLength = $ballScrewLength\"\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5093e6ea-35db-47c2-953b-81253a0f20dc",
   "metadata": {},
   "outputs": [],
   "source": [
    "val mesh = OpenSCAD(FrontPlate.model.rotateX(90).moveY(FrontPlate.height))\n",
    "Viewer(mesh)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ff2418a5-9fa3-4451-9b26-2eb4102d7bde",
   "metadata": {},
   "outputs": [],
   "source": [
    "//the model is upside-down\n",
    "object Base extends SimplePart(\"Base\") {\n",
    "    def width = 200 mm\n",
    "    def height = 20 mm\n",
    "    def depth = (200 mm) /* table bottom plate */ +\n",
    "                (115 mm) /* table middle plate overhang*/ +\n",
    "                (20 mm) /* clearance from the top plate */ +\n",
    "                Pillar.pillarWidth\n",
    "    // mounting holes for the table (should be threaded!)\n",
    "    val tableMountingHoles = Seq((width/2 - Table.mountingHolesWidth /2, 100 - Table.mountingHolesDepth / 2),\n",
    "                                 (width/2 + Table.mountingHolesWidth /2, 100 - Table.mountingHolesDepth / 2),\n",
    "                                 (width/2 - Table.mountingHolesWidth /2, 100 + Table.mountingHolesDepth / 2),\n",
    "                                 (width/2 + Table.mountingHolesWidth /2, 100 + Table.mountingHolesDepth / 2))\n",
    "    // countersunk holes to mount the pillar\n",
    "    val pillarMountingHoles = {\n",
    "        val widthDifference = (pillarInnerspace + Pillar.height) / 2\n",
    "        Pillar.baseHolesPositions.map( y => (width/2 + widthDifference, depth - y) ) ++\n",
    "        Pillar.baseHolesPositions.map( y => (width/2 - widthDifference, depth - y) )\n",
    "    }\n",
    "    \n",
    "    def holes = {\n",
    "        tableMountingHoles.map{ case (x,y) => (Side.Top, HoleSpec(x, y, Table.mountingHoles, height, false, true)) } ++\n",
    "        pillarMountingHoles.map{ case (x,y) => (Side.Top, HoleSpec(x, y, Pillar.baseHoles, height, true, false)) }\n",
    "    }\n",
    "\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fb70fb68-8ae8-4398-92e0-45380e33de9e",
   "metadata": {},
   "outputs": [],
   "source": [
    "object CarriageDimenions {\n",
    "    val sideThickness = 10 mm\n",
    "    val frontThickness = 10 mm\n",
    "    val backThickness = 6 mm\n",
    "    \n",
    "    val frontBackClearance = 5 mm\n",
    "    \n",
    "    val height = carriageHeight\n",
    "    val frontHeight = height\n",
    "    val backHeight = BallScrew.nutLength\n",
    "    val backHeightOffset = 50 mm\n",
    "    val innerWidth = pillarInnerspace + Pillar.height * 2 + LinearRail.totalHeight * 2\n",
    "    val outerWidth = innerWidth + sideThickness * 2\n",
    "    val sideDepth = Pillar.pillarWidth +\n",
    "                    frontBackClearance * 2\n",
    "    val depth = sideDepth +\n",
    "                frontThickness +\n",
    "                backThickness\n",
    "    val upperGuideHeight = LinearGuide.length / 2 + 5\n",
    "    val lowerGuideHeight = height - upperGuideHeight\n",
    "    val guideDepth = sideDepth / 2\n",
    "    \n",
    "    val frontBackHole = ISO.M4\n",
    "    val frontHolesPositions = holesPosition1(4, frontHeight, frontBackHole * 3)\n",
    "    val backHolesPositions = holesPosition1(3, backHeight, frontBackHole * 3)\n",
    "    \n",
    "    val cantileverWidth = SpindleClamp.width\n",
    "    val cantileverDepth = Base.depth -\n",
    "                          100 /* to middle of table */ -\n",
    "                          Pillar.pillarWidth / 2 /* to linear rail */ -\n",
    "                          depth / 2 /* front of carriage */ -\n",
    "                          sideThickness /* frontplate */ -\n",
    "                          SpindleClamp.backToCenter -\n",
    "                          Table.yOffset\n",
    "    val cantileverHeight = cantileverWidth // + backThickness\n",
    "    val cantileverHoles = ISO.M5 // or M6 ?\n",
    "    \n",
    "    val cantileverHolesPositions = {\n",
    "        val x = (cantileverWidth - sideThickness) / 2\n",
    "        val z1 = sideThickness / 2 + 2\n",
    "        val z3 = cantileverHeight - sideThickness / 2 - 2\n",
    "        val z2 = (z1 + z3) / 2\n",
    "        Seq((x,z1),(x,z2),(x,z3),(-x,z1),(-x,z2),(-x,z3))\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d09262aa-32e5-4505-aed1-c4f6a575e9db",
   "metadata": {},
   "outputs": [],
   "source": [
    "object CarriageBack extends SimplePart(\"Carriage Back\") {\n",
    "    import CarriageDimenions._\n",
    "    \n",
    "    def width = outerWidth\n",
    "    def depth = backHeight\n",
    "    def height = backThickness\n",
    "    \n",
    "    def holes = {\n",
    "        // holes to attach to the ballscrew nut\n",
    "        BallScrew.nutHolesPattern.map{ case (y,x) => (Side.Top, HoleSpec(width / 2 + x, depth / 2 + y, BallScrew.nutHoles, height, false, true)) } ++\n",
    "        // holes to attach to side\n",
    "        backHolesPositions.map( y => (Side.Top, HoleSpec(sideThickness/2, y, frontBackHole, height)) ) ++\n",
    "        backHolesPositions.map( y => (Side.Top, HoleSpec(width - sideThickness/2, y, frontBackHole, height)) )\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b89ac8a1-a438-4a03-b86b-22ab57fb684f",
   "metadata": {},
   "outputs": [],
   "source": [
    "object SpindlePlate extends SimplePart(\"Spindle Plate\") {\n",
    "    import CarriageDimenions._\n",
    "    \n",
    "    def width = cantileverWidth\n",
    "    def depth = cantileverHeight + SpindleClamp.height\n",
    "    def height = sideThickness\n",
    "    \n",
    "    def holes = {\n",
    "        cantileverHolesPositions.map{ case (x,y) => (Side.Top, HoleSpec(cantileverWidth/2+x, SpindleClamp.height + y, cantileverHoles, height)) } ++\n",
    "        SpindleClamp.holesPosition.map( x => (Side.Top, HoleSpec(x, SpindleClamp.height/2, SpindleClamp.mountingHoles, height)))\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "049d02c1-ecb4-40a6-8fb6-815830abef03",
   "metadata": {},
   "outputs": [],
   "source": [
    "object CantileverTop extends SimplePart(\"Cantilever Top\") {\n",
    "    import CarriageDimenions._\n",
    "    \n",
    "    def width = cantileverWidth\n",
    "    def depth = cantileverDepth + frontThickness * 2\n",
    "    def height = backThickness\n",
    "    \n",
    "    val topScrew = ISO.M3\n",
    "    val screwOffset = 20 mm\n",
    "    \n",
    "    def holes = {\n",
    "        val s = sideThickness / 2\n",
    "        val d = frontThickness + screwOffset\n",
    "        val hs = Seq(\n",
    "            HoleSpec(s, d, topScrew, height),\n",
    "            HoleSpec(width - s, d, topScrew, height),\n",
    "            HoleSpec(s, depth - d, topScrew, height),\n",
    "            HoleSpec(width - s, depth - d, topScrew, height)\n",
    "        )\n",
    "        hs.map( (Side.Top, _) )\n",
    "    }\n",
    "    \n",
    "    override def otherFeatures: Seq[SubtractiveFeature] = Seq(\n",
    "        PocketSpec(0, 0, sideThickness, depth, 2),\n",
    "        PocketSpec(width - sideThickness, 0, sideThickness, depth, 2),\n",
    "        PocketSpec(0, 0, cantileverWidth, frontThickness, 2),\n",
    "        PocketSpec(0, depth - frontThickness, cantileverWidth, frontThickness, 2)\n",
    "    )\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fbeb2c8e-57c8-452c-93b5-cde289b8e26d",
   "metadata": {},
   "outputs": [],
   "source": [
    "// Rotated on the side\n",
    "object CantileverSide extends SimplePart(\"Cantilever Side\") {\n",
    "    import CarriageDimenions._\n",
    "\n",
    "    def width = cantileverHeight\n",
    "    def depth = cantileverDepth\n",
    "    def height = sideThickness\n",
    "    \n",
    "    def holes = {\n",
    "        // holes to attach the top\n",
    "        def topS(x: Length, y: Length) = (Side.Right, HoleSpec(x, y, CantileverTop.topScrew, 10, threaded = true))\n",
    "        val ts = Seq(topS(sideThickness/2, CantileverTop.screwOffset), topS(sideThickness/2, depth - CantileverTop.screwOffset))\n",
    "        // holes on the back + front of the sides\n",
    "        def fbS(x: Length, y: Length, side: Side.Side) = (side, HoleSpec(x, y, cantileverHoles, 15, threaded = true))\n",
    "        val fs = cantileverHolesPositions.map{ case(x,z) => fbS(z, height/2, Side.Front) }\n",
    "        val bs = cantileverHolesPositions.map{ case(x,z) => fbS(z, height/2, Side.Back) }\n",
    "        ts ++ fs ++ bs\n",
    "    }\n",
    "    \n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ab0ddb20-19d7-4cfe-b6b2-09b6904a5bf5",
   "metadata": {},
   "outputs": [],
   "source": [
    "object CarriageFront extends FlatPart(\"Carriage Front\") {\n",
    "    import CarriageDimenions._\n",
    "    \n",
    "    def width = outerWidth\n",
    "    def depth = frontHeight\n",
    "    def height = frontThickness\n",
    "    \n",
    "    def holes = {\n",
    "        def frontBackScrew(x: Length, y: Length) = (Side.Top, HoleSpec(x, y, frontBackHole, height))\n",
    "        def cantileverScrew(x: Length, y: Length) = (Side.Top, HoleSpec(x, y, cantileverHoles, height))\n",
    "        // holes to attach to side\n",
    "        frontHolesPositions.map( y => frontBackScrew(sideThickness/2, y) ) ++\n",
    "        frontHolesPositions.map( y => frontBackScrew(width - sideThickness/2, y) ) ++\n",
    "        // holes to attach the cantilever\n",
    "        cantileverHolesPositions.map{ case (x,y) => cantileverScrew(width/2+x, depth - cantileverHeight + y) }\n",
    "    }\n",
    "    \n",
    "    val kneeWidth = pillarInnerspace + Pillar.height * 2 + 10\n",
    "    \n",
    "    def baseModel = {\n",
    "        val f0 = Cube(width, depth, height)\n",
    "        // remove material to go over the pillar's knee\n",
    "        \n",
    "        val f1 = Cube(kneeWidth, Pillar.kneeDepth + 5, height).moveX((width - kneeWidth) / 2)\n",
    "        f0 - f1\n",
    "    }\n",
    "    \n",
    "    def baseShape: Path = {\n",
    "        val wk1 = (width - kneeWidth) / 2\n",
    "        val wk2 = width - wk1\n",
    "        val kh = Pillar.kneeDepth + 5\n",
    "        val points = Seq[(Length, Length)](\n",
    "            (0, 0),\n",
    "            (wk1, 0),\n",
    "            (wk1, kh),\n",
    "            (wk2, kh),\n",
    "            (wk2, 0),\n",
    "            (_width, 0),\n",
    "            (_width, _depth),\n",
    "            (0, _depth),\n",
    "            (0, 0)\n",
    "        )\n",
    "        val lines = points.sliding(2).map( s => Line(s(0)._1.to(Millimeters),\n",
    "                                                     s(0)._2.to(Millimeters),\n",
    "                                                     s(1)._1.to(Millimeters),\n",
    "                                                     s(1)._2.to(Millimeters)) )\n",
    "        Path(lines.toIndexedSeq)\n",
    "    }\n",
    "\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cdc64df5-9e15-4e4b-ac1a-a6ba1eab401e",
   "metadata": {},
   "outputs": [],
   "source": [
    "object CarriageSide extends SimplePart(\"Carriage Side\") {\n",
    "    import CarriageDimenions._\n",
    "    \n",
    "    def width = sideDepth\n",
    "    def depth = CarriageDimenions.height\n",
    "    def height = sideThickness\n",
    "    \n",
    "    def holes = {\n",
    "        // holes to mount the guides\n",
    "        def guideScrew(x: Length, y: Length) = (Side.Top, HoleSpec(x, y, LinearGuide.holesRadius, height))\n",
    "        val hg1 = LinearGuide.holePattern.map{ case (x,y) => guideScrew(guideDepth + y, upperGuideHeight + x) }\n",
    "        val hg2 = LinearGuide.holePattern.map{ case (x,y) => guideScrew(guideDepth + y, lowerGuideHeight + x) }\n",
    "        // holes to mount the front\n",
    "        def frontBackScrew(x: Length, y: Length, side: Side.Side) = (side, HoleSpec(x, y, frontBackHole, 15, threaded = true))\n",
    "        val f = frontHolesPositions.map( y => frontBackScrew(sideThickness/2, y, Side.Left))\n",
    "        // holes to mount the back\n",
    "        val b = backHolesPositions.map( y => frontBackScrew(sideThickness/2, depth - backHeight - backHeightOffset + y, Side.Right) )\n",
    "        hg1 ++ hg2 ++ f ++ b\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "abccfae5-7469-4951-a2b8-d67f969569a4",
   "metadata": {},
   "outputs": [],
   "source": [
    "object Carriage {\n",
    "    import CarriageDimenions._\n",
    "\n",
    "    def side = SinglePart(CarriageSide, _.rotateX(90).rotateZ(90))\n",
    "        \n",
    "    def back = SinglePart(CarriageBack, _.rotateX(90).moveY(CarriageBack.height))\n",
    "    \n",
    "    def cantilever = {\n",
    "        // TODO simplify the transforms\n",
    "        val parts: Seq[(Structure, Seq[Solid => Solid])] = Seq(\n",
    "            SinglePart(CantileverSide, (s: Solid) => s.rotateY(-90).moveX(CantileverSide.height)) ->\n",
    "                Seq[Solid => Solid]( s => s.moveX(-cantileverWidth/2), s => s.moveX(cantileverWidth/2 - sideThickness) ),\n",
    "            SinglePart(CantileverTop, (s: Solid) => s.rotateY(180).move(CantileverTop.width, 0, CantileverTop.height - 2)) ->\n",
    "                Seq[Solid => Solid]( s => s.move(-cantileverWidth/2, -frontThickness, cantileverHeight) )\n",
    "        )\n",
    "        Composite(parts)\n",
    "    }\n",
    "    \n",
    "    def front = SinglePart(CarriageFront, _.rotateX(90).moveY(CarriageFront.height))\n",
    "    \n",
    "    def id = Seq[Solid => Solid](s => s)\n",
    "    \n",
    "    def sideWithGuides(left: Boolean = true) = {\n",
    "        val guides = if (left) {\n",
    "            LinearGuide.placeholder -> Seq[Solid => Solid](\n",
    "                _.rotateY(-90).rotateZ(180).moveX(sideThickness).move(0, guideDepth, lowerGuideHeight),\n",
    "                _.rotateY(-90).rotateZ(180).moveX(sideThickness).move(0, guideDepth, upperGuideHeight))\n",
    "        } else {\n",
    "            LinearGuide.placeholder -> Seq[Solid => Solid](\n",
    "                _.rotateY(-90).move(0, guideDepth, lowerGuideHeight),\n",
    "                _.rotateY(-90).move(0, guideDepth, upperGuideHeight))\n",
    "        }\n",
    "        val parts: Seq[(Structure, Seq[Solid => Solid])] = Seq(\n",
    "            guides,\n",
    "            side -> id\n",
    "        )\n",
    "        Composite(parts)\n",
    "    }\n",
    "    \n",
    "    def spindle = {\n",
    "        val parts: Seq[(Structure, Seq[Solid => Solid])] = Seq(\n",
    "            SinglePart(SpindlePlate) -> Seq(_.rotateX(90).moveY(SpindlePlate.height)),\n",
    "            SpindleClamp.placeholder -> Seq(_.rotateZ(180).moveX(SpindleClamp.width))\n",
    "        )\n",
    "        Composite(parts)\n",
    "    }\n",
    "    \n",
    "    def apply() = {\n",
    "        val parts: Seq[(Structure, Seq[Solid => Solid])] = Seq(\n",
    "            sideWithGuides(true) -> Seq(_.moveX(-outerWidth/2)),\n",
    "            sideWithGuides(false) -> Seq(_.moveX(outerWidth/2 - CarriageSide.height)),\n",
    "            front -> Seq(_.move(-outerWidth/2, -frontThickness, 0)),\n",
    "            back -> Seq(_.move(-outerWidth/2, sideDepth, height - backHeight - backHeightOffset)),\n",
    "            cantilever -> Seq(_.move(0, -cantileverDepth -frontThickness, height - cantileverHeight)),\n",
    "            spindle -> Seq(_.move(-cantileverWidth/2, -cantileverDepth - frontThickness - sideThickness, height - (cantileverHeight + SpindleClamp.height)))\n",
    "        )\n",
    "        Composite(parts)\n",
    "    }\n",
    "}\n",
    "//TODO splindle plate should be thicker and have countersunk screw ? or go for some kind of angle brackets / side bar ?\n",
    "//TODO countersink on the front plate\n",
    "//TODO save some material on the front plate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6a2b12c3-a1ff-4a0e-a363-a1ebf1db6844",
   "metadata": {},
   "outputs": [],
   "source": [
    "val mesh = OpenSCAD(Carriage().model)\n",
    "Viewer(mesh)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3ea02a5b-cbb4-4d97-9afb-a818e4a0b26f",
   "metadata": {},
   "outputs": [],
   "source": [
    "OpenSCAD.toSTL(Carriage().model, \"carriage.stl\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "da254c87-0bf3-40bc-aba4-dfa6578b353e",
   "metadata": {},
   "source": [
    "### Together"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "028a9bc5-a09a-4497-8119-1f2a7b753196",
   "metadata": {},
   "outputs": [],
   "source": [
    "object Cnc {\n",
    "    \n",
    "    def base = SinglePart(Base, _.rotateY(180).move(Base.width, 0, Base.height))\n",
    "    \n",
    "    def pillar(left: Boolean) = {\n",
    "        val lt = if(left) {\n",
    "            Seq[Solid => Solid](_.rotateY(-90).moveY(Pillar.pillarWidth/2))\n",
    "        } else {\n",
    "            Seq[Solid => Solid](_.rotateY(-90).rotateZ(180).move(Pillar.height, Pillar.pillarWidth/2, 0))\n",
    "        }\n",
    "        Composite(Seq[(Structure, Seq[Solid => Solid])](\n",
    "            SinglePart(Pillar) -> Seq(_.rotateX(90).rotateZ(-90).move(Pillar.height,Pillar.pillarWidth,0)),\n",
    "            LinearRail.placeholder(Pillar.railLength) -> lt\n",
    "        ))\n",
    "    }\n",
    "    \n",
    "    def column = Composite(Seq[(Structure, Seq[Solid => Solid])](\n",
    "        pillar(true) -> Seq(_.move(-pillarInnerspace / 2 - Pillar.height, 0, 0)),\n",
    "        pillar(false) -> Seq(_.move(pillarInnerspace / 2, 0, 0)),\n",
    "        SinglePart(FrontPlate) -> Seq(_.rotateX(90).moveY(FrontPlate.height).move(-FrontPlate.width/2, 0, 0)),\n",
    "        BallScrew.placeholder(FrontPlate.ballScrewLength) -> Seq(_.rotateY(-90).rotateZ(-90).moveZ(FrontPlate.depth - 10 - FrontPlate.ballScrewLength))\n",
    "    ))\n",
    "    \n",
    "    def apply() = Composite(Seq[(Structure, Seq[Solid => Solid])](\n",
    "        base -> Seq(_.move(-Base.width / 2, 0 , -Base.height)),\n",
    "        column -> Seq(_.move(0, Base.depth - Pillar.pillarWidth, 0)),\n",
    "        Carriage() -> Seq(_.move(0, Base.depth - CarriageDimenions.sideDepth + CarriageDimenions.frontBackClearance, 200)),\n",
    "        Table.placeholder -> Seq(_.moveY(100))\n",
    "    ))\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ddb7292e-8af8-4019-9e56-fdf834e3b449",
   "metadata": {},
   "outputs": [],
   "source": [
    "val mesh = OpenSCAD(Cnc().model)\n",
    "Viewer(mesh)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3edb821c-27d8-49d0-9fe2-446c59f60a02",
   "metadata": {},
   "outputs": [],
   "source": [
    "OpenSCAD.toSTL(Cnc().model, \"cnc.stl\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c2bd225c-8df0-407c-8232-180713c0385a",
   "metadata": {},
   "source": [
    "### List of parts"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3e787aea-6e5f-40ee-8689-e527b7cd8704",
   "metadata": {},
   "outputs": [],
   "source": [
    "println(Cnc().info)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "41b12f22-04cb-4415-b467-a3588dd60ce5",
   "metadata": {},
   "source": [
    "## Gearbox to hold the motor and handwheel\n",
    "\n",
    "For the gear, we will use some files from Thingiverse.\n",
    "The gears are CC-BY-SA by GeneralRulofDumb, see https://www.thingiverse.com/thing:10955.\n",
    "\n",
    "The gears (original scale) are offset `12.1 mm` from the intersection of the two rotation axes."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "04b2c735-fe27-4f03-ad64-0273901e786b",
   "metadata": {},
   "outputs": [],
   "source": [
    "// get the bevel gear\n",
    "import java.nio.file.{Paths, Files}\n",
    "import java.net.{HttpURLConnection,URL}\n",
    "\n",
    "val gearLeft = FromFile(\"gear_hypoid_left.stl\")\n",
    "val gearRight = FromFile(\"gear_hypoid_right.stl\")\n",
    "\n",
    "val gearLeftURL = \"https://cdn.thingiverse.com/assets/08/c0/2b/0d/90/gear_hypoid_left.stl\"\n",
    "val gearRightURL = \"https://cdn.thingiverse.com/assets/e8/ab/bd/72/48/gear_hypoid_right.stl\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b73cc31b-3dc5-44a5-8e0b-c70817864fbb",
   "metadata": {},
   "outputs": [],
   "source": [
    "def getFile(address: String, file: String) = {\n",
    "    if (!Files.exists(Paths.get(file))) {\n",
    "        val url = new URL(address)\n",
    "        val connection = url.openConnection().asInstanceOf[HttpURLConnection]\n",
    "        connection.connect()\n",
    "        try {\n",
    "            val code = connection.getResponseCode\n",
    "            if (code != 200) {\n",
    "                println(\"error \" + code)\n",
    "            } else {\n",
    "                url #> new File(file) !!\n",
    "            }\n",
    "        } finally {\n",
    "            connection.close()\n",
    "        }\n",
    "    }\n",
    "}\n",
    "\n",
    "getFile(gearLeftURL, gearLeft)\n",
    "getFile(gearRightURL, gearRight)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "883cad4c-e994-4bb1-9701-679dd4b4c6b9",
   "metadata": {},
   "source": [
    "This part is designed to be 3D printed rather than milled.\n",
    "\n",
    "The faceplate for a nema motor is\n",
    "- `56.4 mm` wide\n",
    "- holes are `47.14 mm` apart\n",
    "- center flange is `38.1mm` in diameter"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f49a47e8-39e6-41d6-b04a-17fee2d4f63d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Scala",
   "language": "scala",
   "name": "scala"
  },
  "language_info": {
   "codemirror_mode": "text/x-scala",
   "file_extension": ".sc",
   "mimetype": "text/x-scala",
   "name": "scala",
   "nbconvert_exporter": "script",
   "version": "2.13.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
