{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b4ca53e7-d9e2-4530-ad3f-5e9266e29a8d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import coursierapi._\n",
    "interp.repositories() ++= Seq(MavenRepository.of(\"https://jitpack.io\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "85a49b11-7bb7-4527-b747-415ca011f382",
   "metadata": {},
   "outputs": [],
   "source": [
    "import $ivy.`com.github.dzufferey::scadla:0.1.1`\n",
    "import scadla._\n",
    "import InlineOps._\n",
    "import EverythingIsIn.{millimeters, degrees}\n",
    "import scadla.utils.thread.ISO\n",
    "import scadla.utils.CenteredCube\n",
    "import squants.space.{Length, Millimeters}\n",
    "import scala.language.postfixOps\n",
    "import squants.space.LengthConversions._\n",
    "import scadla.backends.OpenSCAD // for rendering (getting a mesh)\n",
    "import scadla.backends.almond.Viewer // to show the mesh in jupyter/almond"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d17a5db8-b09b-414a-849f-5e1cca063ec8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import $ivy.`com.github.dzufferey::libgcode:0.1-SNAPSHOT`\n",
    "import libgcode.utils.{Viewer => NcViewer}\n",
    "import libgcode._\n",
    "import libgcode.extractor._\n",
    "import libgcode.generator._\n",
    "import libgcode.utils._\n",
    "import libgcode.utils.geometry2D._\n",
    "import scala.collection.mutable.ArrayBuffer"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ba3cc5c7-f44e-48ee-b456-f74bf2643c10",
   "metadata": {},
   "source": [
    "# New Z-axis for my cnc"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1f633855-a020-43c9-b361-46fc89fc1363",
   "metadata": {},
   "source": [
    "## Dimensions for mechanical components"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ad54d150-ad85-4422-b775-b554d30add37",
   "metadata": {},
   "outputs": [],
   "source": [
    "// linear rails (MGN 15C)\n",
    "object LinearRail {\n",
    "    val totalHeight = 16 mm // surface to surface distance includes rail + guide\n",
    "    val width = 15 mm\n",
    "    val height = 10 mm\n",
    "    val holesDistance = 40 mm\n",
    "    val holesRadius = ISO.M3\n",
    "    def screwPositions(length: Length) = { // x coord of the mounting screw\n",
    "        val n = ((length - holesRadius * 2) / holesDistance).floor.toInt\n",
    "        val offset = (length - holesDistance * n) / 2\n",
    "        (0 until n).map( i => offset + holesDistance * i)\n",
    "    }\n",
    "    // extend in x direction [0, length], y centered at 0, back against xy plane\n",
    "    def rail(length: Length) = {\n",
    "        val r = Cube(length, width, height).moveY(- width / 2)\n",
    "        val screw = Cylinder(holesRadius, height) + Cylinder(holesRadius * 2, holesRadius).moveZ(height - holesRadius + 0.1)\n",
    "        val hs = screwPositions(length).map( x => screw.moveX(x) )\n",
    "        r -- hs\n",
    "    }\n",
    "    def holePattern(length: Length, h: Length = 10) = {\n",
    "        val screw = Cylinder(holesRadius, h+1).moveZ(-h)\n",
    "        screwPositions(length).map( x => screw.moveX(x) )\n",
    "    }\n",
    "}\n",
    "object LinearGuide {\n",
    "    val length = 42.1 mm\n",
    "    val width = 32 mm\n",
    "    val height = 12 mm\n",
    "    val holesLength = 20 mm\n",
    "    val holesWidth = 25 mm\n",
    "    val holesRadius = ISO.M3\n",
    "    // centered at (0,0), back at 0 and guide facing up\n",
    "    val holePattern = Seq(( holesLength / 2,  holesWidth / 2),\n",
    "                          (-holesLength / 2,  holesWidth / 2),\n",
    "                          ( holesLength / 2, -holesWidth / 2),\n",
    "                          (-holesLength / 2, -holesWidth / 2))\n",
    "    val model = {\n",
    "        val c0 = CenteredCube.xy(length, width, height)\n",
    "        val c1 = c0 - CenteredCube.xy(length, LinearRail.width, LinearRail.height).moveZ(4)\n",
    "        c1 -- holePattern.map{ case (x,y) => Cylinder(holesRadius, height).move(x, y, 0) } // make througholes to see align\n",
    "    }\n",
    "}\n",
    "// ballscrew\n",
    "object BallScrew {\n",
    "    // https://www.dold-mechatronik.de/Spindelmuttergehaeuse-DSG1605-fuer-Kugelumlaufspindel-SFU1605-SFU1610\n",
    "    val nutHeight = 40 mm\n",
    "    val nutWidth = 52 mm\n",
    "    val nutLength = 40 mm\n",
    "    val nutHoles = ISO.M5\n",
    "    val nutHolesDistanceWidth = 40 mm\n",
    "    val nutHolesDistanceLength = 24 mm\n",
    "    val nutHolesPattern = Seq(( nutHolesDistanceLength / 2,  nutHolesDistanceWidth / 2),\n",
    "                              (-nutHolesDistanceLength / 2,  nutHolesDistanceWidth / 2),\n",
    "                              ( nutHolesDistanceLength / 2, -nutHolesDistanceWidth / 2),\n",
    "                              (-nutHolesDistanceLength / 2, -nutHolesDistanceWidth / 2))\n",
    "    // https://www.dold-mechatronik.de/Festlagereinheit-FLB20-3200-Easy-Mechatronics-System-1620B\n",
    "    val endHeight = 51 mm\n",
    "    val endWidth = 70 mm\n",
    "    val endDepth = 20 mm\n",
    "    val endHolesDistance = 55 mm\n",
    "    val endHoles = ISO.M6\n",
    "    val endHolesPattern = Seq(-endHolesDistance / 2, endHolesDistance / 2)\n",
    "    val bottomToRotationAxis = 31 mm\n",
    "    val bearingUnit = {\n",
    "        val c0 = CenteredCube.xy(endDepth, 40, endHeight)\n",
    "        val c1 = c0 + CenteredCube.xy(endDepth, endWidth, 10)\n",
    "        val c2 = c1 -- endHolesPattern.map( y => Cylinder(endHoles, 11).moveY(y) )\n",
    "        c2\n",
    "    }\n",
    "    // length is the distance between mounting screw\n",
    "    def model(l: Length) = {\n",
    "        bearingUnit + bearingUnit.moveX(l) + Cylinder(10, l).rotateY(90).moveZ(bottomToRotationAxis)\n",
    "    }\n",
    "}\n",
    "// spindle clamp: https://www.dold-mechatronik.de/Eurohalsaufnahme-65x75x20\n",
    "object SpindleClamp {\n",
    "    val width = 65 mm\n",
    "    val height = 20 mm\n",
    "    val depth = 75 mm\n",
    "    val backToCenter = 42 mm\n",
    "    val centerDiameter = 43 mm\n",
    "    val centerGap = 2 mm\n",
    "    val mountingHoles = ISO.M8\n",
    "    val holesPosition = Seq(7.5 mm, 32.5 mm, 57.5 mm)\n",
    "    val holesHeight = 10 mm\n",
    "    val model = {\n",
    "        val x0 = Cube(width, depth, height)\n",
    "        val x1 = x0 - Cylinder(centerDiameter/2, height).move(width/2, backToCenter, 0)\n",
    "        val x2 = x1 - CenteredCube.x(centerGap, depth, height).move(width/2, backToCenter + 1, 0)\n",
    "        val screw = Cylinder(mountingHoles, 17).rotateX(-90)\n",
    "        val x3 = x2 -- holesPosition.map( x => screw.move(x, 0, height / 2) )\n",
    "        x3\n",
    "    }\n",
    "}\n",
    "\n",
    "def holesPosition0(n: Int, start: Length, end: Length) = {\n",
    "    val delta = (end - start) / (n-1)\n",
    "    (0 until n).map( i => start + delta * i )\n",
    "}\n",
    "\n",
    "def holesPosition1(n: Int, length: Length, distanceToBorder: Length) = {\n",
    "    holesPosition0(n, distanceToBorder, length - distanceToBorder)\n",
    "}"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6a5574b2-c138-4cd1-a2d2-92d8cd805668",
   "metadata": {},
   "source": [
    "## XY table (already made)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c9bff178-36d7-43a9-8baf-0660a716a7c9",
   "metadata": {},
   "outputs": [],
   "source": [
    "object Table {\n",
    "    val mountingHolesWidth = 160 mm\n",
    "    val mountingHolesDepth = 80 mm\n",
    "    val mountingHoles = ISO.M8\n",
    "    val xTravel = 300 mm\n",
    "    val yTravel = 200 mm\n",
    "    val distBetweenPlates = BallScrew.nutHeight / 2 +  BallScrew.bottomToRotationAxis\n",
    "    val plateThickness = 20 mm\n",
    "    val totalHeigth = plateThickness * 3 + distBetweenPlates * 2\n",
    "    def placeholder(x: Double = 0.5, y: Double = 0.5) = {\n",
    "        val lower = CenteredCube.xy(550, 200, plateThickness)\n",
    "        val mz = plateThickness + distBetweenPlates\n",
    "        val xPos = xTravel * (0.5 - x)\n",
    "        val middle = CenteredCube.x(200, 350, plateThickness).move(xPos, -130, mz)\n",
    "        val uz = mz * 2\n",
    "        val yPos = yTravel * (1 - y)\n",
    "        val upper = CenteredCube.xy(300, 200, plateThickness).move(xPos, yPos - 55, uz)\n",
    "        lower + middle + upper\n",
    "    }\n",
    "    val xOffset = 0 mm\n",
    "    val yOffset = 45 mm\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2fabb911-9113-4a50-8b81-056d87bb0641",
   "metadata": {},
   "outputs": [],
   "source": [
    "val mesh = OpenSCAD(Table.placeholder())\n",
    "Viewer(mesh)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b38e9edc-3cf6-4d1f-9d02-2b5c3549ea59",
   "metadata": {},
   "outputs": [],
   "source": [
    "case class HoleSpec(\n",
    "    x: Length,\n",
    "    y: Length,\n",
    "    radius: Length,\n",
    "    depth: Length,\n",
    "    counterBore: Boolean = false,\n",
    "    threaded: Boolean = false\n",
    ") {\n",
    "    protected def counterBoreRadius = if (counterBore) 2*radius.to(Millimeters) else 0\n",
    "    protected def counterBoreDepth = if (counterBore) radius.to(Millimeters) else 0\n",
    "    protected def _x = x.to(Millimeters)\n",
    "    protected def _y = y.to(Millimeters)\n",
    "    protected def _radius = radius.to(Millimeters)\n",
    "    protected def _depth = depth.to(Millimeters)\n",
    "    def model(z: Length, extra: Length = 0.1 mm) = {\n",
    "        val m0 = Cylinder(radius, depth + extra)\n",
    "        val m1 = Cylinder(counterBoreRadius, counterBoreDepth + extra).moveZ(depth - counterBoreDepth)\n",
    "        val m2 = m0 + m1\n",
    "        m2.move(x, y, z - depth)\n",
    "    }\n",
    "    def spot(z: Length, ignoreCounterBore: Boolean = false)(implicit conf: Config): Seq[Command] = {\n",
    "        val _z = z.to(Millimeters)\n",
    "        if (ignoreCounterBore) {\n",
    "            Drill(_x, _y, _z, conf.endmillRadius)\n",
    "        } else {\n",
    "            Drill(_x, _y, _z - counterBoreDepth, conf.endmillRadius)\n",
    "        }\n",
    "    }\n",
    "    def drill(z: Length, ignoreCounterBore: Boolean = false)(implicit conf: Config): Seq[Command] = {\n",
    "        val _z = z.to(Millimeters)\n",
    "        if (ignoreCounterBore) {\n",
    "            Drill(_x, _y, _z, _depth)\n",
    "        } else {\n",
    "            Drill(_x, _y, _z - counterBoreDepth, _depth - counterBoreDepth)\n",
    "        }\n",
    "    }\n",
    "    protected def threadingHole(radius: Length) = {\n",
    "        implicit val tolerance = (1e-6 mm)\n",
    "        if (radius ~= ISO.M1_6) 1.25 / 2\n",
    "        else if (radius ~= ISO.M2) 0.8\n",
    "        else if (radius ~= ISO.M2_5) 1\n",
    "        else if (radius ~= ISO.M3) 1.25\n",
    "        else if (radius ~= ISO.M4) 1.6\n",
    "        else if (radius ~= ISO.M5) 2.1\n",
    "        else if (radius ~= ISO.M6) 2.5\n",
    "        else if (radius ~= ISO.M8) 3.4\n",
    "        else if (radius ~= ISO.M10) 4.25\n",
    "        else if (radius ~= ISO.M12) 5\n",
    "        else radius.to(Millimeters) * 0.4\n",
    "    }\n",
    "    def toolpath(z: Length, ignoreShaft: Boolean = false)(implicit conf: Config): Seq[Command] = {\n",
    "        val _z = z.to(Millimeters)\n",
    "        val buffer = scala.collection.mutable.ArrayBuffer.empty[Command]\n",
    "        if (counterBore) {\n",
    "            buffer ++= Hole(_x, _y, _z, counterBoreRadius, counterBoreDepth)\n",
    "        }\n",
    "        if (!ignoreShaft) {\n",
    "            var r = if (threaded) threadingHole(radius) else _radius\n",
    "            buffer ++= Hole(_x, _y, _z - counterBoreDepth, r, _depth - counterBoreDepth)\n",
    "        }\n",
    "        buffer.toSeq\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3222eb77-71b1-4779-8e7d-c62dd4aeaf0c",
   "metadata": {},
   "outputs": [],
   "source": [
    "abstract class Part {\n",
    "    def simple: Boolean = false\n",
    "    def model: Solid\n",
    "    def info: String\n",
    "    def contour(width: Length, onionSkin: Length = (0.5 mm))(implicit conf: Config): Seq[Command]\n",
    "    def chamfer(implicit conf: Config): Seq[Command]\n",
    "    def spotHoles(ignoreCounterBore: Boolean = false)(implicit conf: Config): Seq[Command]\n",
    "    def drillHoles(ignoreCounterBore: Boolean = false)(implicit conf: Config): Seq[Command]\n",
    "    def boreHoles(ignoreShaft: Boolean = false)(implicit conf: Config): Seq[Command]\n",
    "}\n",
    "\n",
    "// a simple part is milled from one part with just a rectangle with some holes\n",
    "abstract class SimplePart(name: String) extends Part {\n",
    "    override def simple = true\n",
    "    \n",
    "    def width: Length /* X */\n",
    "    def depth: Length /* Y */\n",
    "    def height: Length /* Z */\n",
    "    def holes: Seq[HoleSpec]\n",
    "    \n",
    "    def model: Solid = {\n",
    "        Cube(width, depth, height) -- holes.map( _.model(height) )\n",
    "    }\n",
    "    \n",
    "    def corners(r: Double) = {\n",
    "        Seq[(Double, Double, Double)] = Seq(\n",
    "            (0, 0, r),\n",
    "            (width.to(Millimeters), 0, r),\n",
    "            (width.to(Millimeters), depth.to(Millimeters), r),\n",
    "            (0, depth.to(Millimeters), r)\n",
    "        )\n",
    "    }\n",
    "    \n",
    "    def contour(width: Length, onionSkin: Length)(implicit conf: Config): Seq[Command] = {\n",
    "        ???\n",
    "    }\n",
    "    \n",
    "    def chamfer(implicit conf: Config): Seq[Command] = {\n",
    "        val r = conf.endmillRadius\n",
    "        Contour(r), height.to(Millimeters) - r)\n",
    "    }\n",
    "    \n",
    "    def spotHoles(ignoreCounterBore: Boolean)(implicit conf: Config): Seq[Command] = {\n",
    "        holes.flatMap( _.spot(height, ignoreCounterBore) )\n",
    "    }\n",
    "    \n",
    "    def drillHoles(ignoreCounterBore: Boolean)(implicit conf: Config): Seq[Command] = {\n",
    "        holes.flatMap( _.drill(height, ignoreCounterBore) )\n",
    "    }\n",
    "    \n",
    "    def boreHoles(ignoreShaft: Boolean)(implicit conf: Config): Seq[Command] = {\n",
    "        holes.flatMap( _.toolpath(height, ignoreShaft) )\n",
    "    }\n",
    "    \n",
    "    def extraInfo: String = \"\"\n",
    "    \n",
    "    def info = {\n",
    "        s\"\"\"|$name:\n",
    "            |  width = $width\n",
    "            |  depth = $depth\n",
    "            |  height = $height\n",
    "            |${extraInfo}\"\"\".stripMargin\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a5b4e99b-17fa-41c7-8971-eb1e688a1236",
   "metadata": {},
   "outputs": [],
   "source": [
    "//TODO more comlex parts\n",
    "//specifying the base shape ...."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f791d414-4461-42d9-b9a4-6cf339db8510",
   "metadata": {},
   "source": [
    "## Draft"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "455dcb9d-8a0d-4469-95cc-cabde9283faa",
   "metadata": {},
   "outputs": [],
   "source": [
    "val carriageHeight = 150 mm\n",
    "val pillarInnerspace = BallScrew.nutWidth.max(BallScrew.endWidth) + 10 //TODO smaller endwidth\n",
    "val expectedTravel = 150 mm\n",
    "\n",
    "//TODO where to put the z-axis stop\n",
    "\n",
    "object Pillar {\n",
    "    val width = 15 mm\n",
    "    val depth = 60 mm\n",
    "    val height = Table.totalHeigth +\n",
    "                 15 /* slots for t-nuts */ +\n",
    "                 30 + /* spindle collet to collar */\n",
    "                 carriageHeight + /* carriage heigth */\n",
    "                 expectedTravel /* expected z travel */\n",
    "    val railLength = height\n",
    "    \n",
    "    val kneeDepth = 50 mm\n",
    "    val kneeHeight = 20 mm\n",
    "    \n",
    "    def totalDepth = depth + kneeDepth\n",
    "    \n",
    "    val baseHoles = ISO.M8\n",
    "    val baseHolesNumber = 3\n",
    "    val baseHolesPositions = {\n",
    "        val l = depth + kneeDepth\n",
    "        val toBorder = baseHoles * 2.5\n",
    "        val dist = (l - toBorder * 2) / (baseHolesNumber - 1)\n",
    "        Seq(toBorder, toBorder + dist + 5, toBorder + dist * 2)\n",
    "    }\n",
    "    \n",
    "    val frontDepth = 6 mm\n",
    "    val frontHole = ISO.M3\n",
    "    val frontHeight = height - kneeHeight\n",
    "    val frontHolesPositions = holesPosition1(6, frontHeight, frontHole * 3 + 10).map( _ + kneeHeight )\n",
    "    \n",
    "    //TODO should fillet the knee\n",
    "    //TODO rail length should be somewhat standard\n",
    "    \n",
    "    def model = {\n",
    "        val p = Cube(width, depth, height)\n",
    "        val k = Cube(width, kneeDepth, kneeHeight)\n",
    "        val s0 = p + k.moveY(-kneeDepth)\n",
    "        // holes to attach\n",
    "        // (1) the base\n",
    "        val s1 = s0 -- baseHolesPositions.map( y => Cylinder(baseHoles, 15).move(width/2, y - kneeDepth, 0) )\n",
    "        // (2) the front\n",
    "        val s2 = s1 -- frontHolesPositions.map( z => Cylinder(frontHole, width).rotateY(90).move(0, frontDepth / 2 , z) )\n",
    "        // (3) the rails\n",
    "        val s3 = s2 -- LinearRail.holePattern(railLength,width).map( _.rotateY(-90).moveY(depth/2) )\n",
    "        s3\n",
    "    }\n",
    "    \n",
    "    def info = {\n",
    "        s\"\"\"|Pillar (2x):\n",
    "            |  width = $width\n",
    "            |  depth = $depth\n",
    "            |  height = $height\n",
    "            |  rail length =  $railLength\"\"\".stripMargin\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "52b18bca-0787-4d0c-a80e-ab489f1bce4c",
   "metadata": {},
   "outputs": [],
   "source": [
    "val mesh = OpenSCAD(Pillar.model)\n",
    "Viewer(mesh)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ea1d6378-fac8-4f5e-917e-41d9a1dab5c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "object FrontPlate {\n",
    "    val width = pillarInnerspace\n",
    "    val depth = Pillar.frontDepth\n",
    "    val height = Pillar.height\n",
    "    val ballScrewLength = expectedTravel + 200 // when I make a lower table, I'll have more travel\n",
    "    \n",
    "    // TODO spacer for the front plate to hold the ballscrew at the proper distance\n",
    "    // TODO to mount the ballscrew attach from the back, tighter holes\n",
    "    // TODO better travel / height ratio ?\n",
    "    \n",
    "    def model = {\n",
    "        val f0 = Cube(width, depth, height)\n",
    "        // holes for pillar\n",
    "        val pd2 = depth / 2\n",
    "        val s = Cylinder(Pillar.frontHole, 10).rotateY(90)\n",
    "        val f1 = f0 -- Pillar.frontHolesPositions.map( z => s.move(0, pd2, z) + s.move(width-10, pd2, z))\n",
    "        // holes for ballscrew\n",
    "        val s2 = Cylinder(BallScrew.endHoles, 10).rotateX(-90)\n",
    "        val h2 = height - 10\n",
    "        val h3 = h2 - ballScrewLength + 10\n",
    "        val f2 = f1 -- BallScrew.endHolesPattern.map( x => s2.move(width/2+x, 0, h2) + s2.move(width/2+x, 0, h3) )\n",
    "        f2\n",
    "    }\n",
    "    \n",
    "    def info = {\n",
    "        s\"\"\"|FrontPlate (1x):\n",
    "            |  width = $width\n",
    "            |  depth = $depth\n",
    "            |  height = $height\n",
    "            |  ballScrewLength = $ballScrewLength\"\"\".stripMargin\n",
    "    }\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5093e6ea-35db-47c2-953b-81253a0f20dc",
   "metadata": {},
   "outputs": [],
   "source": [
    "val mesh = OpenSCAD(FrontPlate.model)\n",
    "Viewer(mesh)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ff2418a5-9fa3-4451-9b26-2eb4102d7bde",
   "metadata": {},
   "outputs": [],
   "source": [
    "//the model is upside-down\n",
    "object Base extends SimplePart(\"Base\") {\n",
    "    def width = 200 mm\n",
    "    def height = 20 mm\n",
    "    def depth = (200 mm) /* table bottom plate */ +\n",
    "                (115 mm) /* table middle plate overhang*/ +\n",
    "                (20 mm) /* clearance from the top plate */ +\n",
    "                Pillar.depth\n",
    "    // mounting holes for the table (should be threaded!)\n",
    "    val tableMountingHoles = Seq((width/2 - Table.mountingHolesWidth /2, 100 - Table.mountingHolesDepth / 2),\n",
    "                                 (width/2 + Table.mountingHolesWidth /2, 100 - Table.mountingHolesDepth / 2),\n",
    "                                 (width/2 - Table.mountingHolesWidth /2, 100 + Table.mountingHolesDepth / 2),\n",
    "                                 (width/2 + Table.mountingHolesWidth /2, 100 + Table.mountingHolesDepth / 2))\n",
    "    // countersunk holes to mount the pillar\n",
    "    val pillarMountingHoles = {\n",
    "        val widthDifference = (pillarInnerspace + Pillar.width) / 2\n",
    "        Pillar.baseHolesPositions.map( y => (width/2 + widthDifference, depth - Pillar.totalDepth + y) ) ++\n",
    "        Pillar.baseHolesPositions.map( y => (width/2 - widthDifference, depth - Pillar.totalDepth + y) )\n",
    "    }\n",
    "    \n",
    "    def holes = {\n",
    "        tableMountingHoles.map{ case (x,y) => HoleSpec(x, y, Table.mountingHoles, height, false, true) } ++\n",
    "        pillarMountingHoles.map{ case (x,y) => HoleSpec(x, y, Pillar.baseHoles, height, true, false) }\n",
    "    }\n",
    "\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1f33c173-664f-4d91-a182-53ed9c6bb251",
   "metadata": {},
   "outputs": [],
   "source": [
    "val mesh = OpenSCAD(Base.model)\n",
    "Viewer(mesh)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e64a56ed-6ade-4e31-b63a-fa650266fbf6",
   "metadata": {},
   "outputs": [],
   "source": [
    "object CarriageDimenions {\n",
    "    val sideThickness = 10 mm\n",
    "    val frontThickness = 10 mm\n",
    "    val backThickness = 6 mm\n",
    "    \n",
    "    val frontBackClearance = 5 mm\n",
    "    \n",
    "    val height = carriageHeight\n",
    "    val frontHeight = height\n",
    "    val backHeight = BallScrew.nutLength\n",
    "    val backHeightOffset = 50 mm\n",
    "    val innerWidth = pillarInnerspace + Pillar.width * 2 + LinearRail.totalHeight * 2\n",
    "    val outerWidth = innerWidth + sideThickness * 2\n",
    "    val sideDepth = Pillar.depth +\n",
    "                    frontBackClearance * 2\n",
    "    val depth = sideDepth +\n",
    "                frontThickness +\n",
    "                backThickness\n",
    "    val upperGuideHeight = LinearGuide.length / 2 + 5\n",
    "    val lowerGuideHeight = height - upperGuideHeight\n",
    "    val guideDepth = sideDepth / 2\n",
    "    \n",
    "    val frontBackHole = ISO.M4\n",
    "    val frontHolesPositions = holesPosition1(4, frontHeight, frontBackHole * 3)\n",
    "    val backHolesPositions = holesPosition1(3, backHeight, frontBackHole * 3)\n",
    "    \n",
    "    val cantileverWidth = SpindleClamp.width\n",
    "    val cantileverDepth = Base.depth -\n",
    "                          100 /* to middle of table */ -\n",
    "                          Pillar.depth / 2 /* to linear rail */ -\n",
    "                          depth / 2 /* front of carriage */ -\n",
    "                          sideThickness /* frontplate */ -\n",
    "                          SpindleClamp.backToCenter -\n",
    "                          Table.yOffset\n",
    "    val cantileverHeight = cantileverWidth // + backThickness\n",
    "    val cantileverHoles = ISO.M5 // or M6 ?\n",
    "    \n",
    "    val cantileverHolesPositions = {\n",
    "        val x = (cantileverWidth - sideThickness) / 2\n",
    "        val z1 = sideThickness / 2 + 2\n",
    "        val z3 = cantileverHeight - sideThickness / 2 - 2\n",
    "        val z2 = (z1 + z3) / 2\n",
    "        Seq((x,z1),(x,z2),(x,z3),(-x,z1),(-x,z2),(-x,z3))\n",
    "    }\n",
    "}\n",
    "\n",
    "object CarriageBack extends SimplePart(\"Carriage Back\") {\n",
    "    import CarriageDimenions._\n",
    "    \n",
    "    def width = outerWidth\n",
    "    def depth = backHeight\n",
    "    def height = backThickness\n",
    "    \n",
    "    def holes = {\n",
    "        // holes to attach to the ballscrew nut\n",
    "        BallScrew.nutHolesPattern.map{ case (y,x) => HoleSpec(width / 2 + x, depth / 2 + y, BallScrew.nutHoles, height, false, true) } ++\n",
    "        // holes to attach to side\n",
    "        backHolesPositions.map( y => HoleSpec(sideThickness/2, y, frontBackHole, height) ) ++\n",
    "        backHolesPositions.map( y => HoleSpec(width - sideThickness/2, y, frontBackHole, height) )\n",
    "    }\n",
    "}\n",
    "\n",
    "object SpindlePlate extends SimplePart(\"Spindle Plate\") {\n",
    "    import CarriageDimenions._\n",
    "    \n",
    "    def width = cantileverWidth\n",
    "    def depth = cantileverHeight + SpindleClamp.height\n",
    "    def height = sideThickness\n",
    "    \n",
    "    def holes = {\n",
    "        cantileverHolesPositions.map{ case (x,y) => HoleSpec(cantileverWidth/2+x, SpindleClamp.height + y, cantileverHoles, height) } ++\n",
    "        SpindleClamp.holesPosition.map( x => HoleSpec(x, SpindleClamp.height/2, SpindleClamp.mountingHoles, height))\n",
    "    }\n",
    "}\n",
    "\n",
    "object Carriage {\n",
    "    import CarriageDimenions._\n",
    "\n",
    "    val frontBackScrew = Cylinder(frontBackHole, 40).moveZ(-20).rotateX(90)\n",
    "    \n",
    "    def side = {\n",
    "        val s0 = Cube(sideThickness, sideDepth, height)\n",
    "        val guideScrew = Cylinder(LinearGuide.holesRadius, height+2).rotateY(90)\n",
    "        // holes to mount the guides\n",
    "        val s1 = s0 -- LinearGuide.holePattern.map{ case (x,y) => guideScrew.move(-1, guideDepth + y, upperGuideHeight + x) }\n",
    "        val s2 = s1 -- LinearGuide.holePattern.map{ case (x,y) => guideScrew.move(-1, guideDepth + y, lowerGuideHeight + x) }\n",
    "        // holes to mount the front\n",
    "        val s3 = s2 -- frontHolesPositions.map( z => frontBackScrew.move(sideThickness/2, 0, z))\n",
    "        // holes to mount the back\n",
    "        val s4 = s3 -- backHolesPositions.map( z => frontBackScrew.move(sideThickness/2, sideDepth, height - backHeight - backHeightOffset + z))\n",
    "        s4\n",
    "    }\n",
    "        \n",
    "    def back = CarriageBack.model.rotateX(90).moveY(CarriageBack.height)\n",
    "    \n",
    "    def cantilever = {\n",
    "        // 3 plates: 2 sides and top\n",
    "        val side = Cube(sideThickness, cantileverDepth, cantileverHeight)\n",
    "        val top = {\n",
    "            val x = cantileverWidth\n",
    "            val y = cantileverDepth + frontThickness * 2 //top goes over the plates where it is attached\n",
    "            val z = backThickness - 2\n",
    "            val c0 = Cube(x, y, z)\n",
    "            val c1 = Cube(x - sideThickness*2, y - frontThickness*2, 2)\n",
    "            c0 + c1.move(sideThickness, frontThickness, -2)\n",
    "        }\n",
    "        val shape = side.moveX(-cantileverWidth/2) +\n",
    "                    side.moveX(cantileverWidth/2 - sideThickness) +\n",
    "                    top.move(-cantileverWidth/2, -frontThickness, cantileverHeight)\n",
    "        // holes on the back + front of the sides\n",
    "        val s0 = Cylinder(cantileverHoles, 30).moveZ(-15).rotateX(90)\n",
    "        val c0 = shape -- cantileverHolesPositions.map{ case(x,z) => s0.move(x,0,z) + s0.move(x,cantileverDepth,z) }\n",
    "        // holes to attach the top\n",
    "        val s1 = Cylinder(ISO.M3, 10).moveZ(cantileverHeight + frontThickness - 10)\n",
    "        val x = (cantileverWidth  - sideThickness) / 2\n",
    "        val y0 = 20 mm // TODO as param\n",
    "        val y1 = cantileverDepth - 20\n",
    "        val pos = Seq((x,y0),(x,y1),(-x,y0),(-x,y1))\n",
    "        val c1 = c0 -- pos.map{ case (x,y) => s1.move(x,y,0) }\n",
    "        c1\n",
    "    }\n",
    "    \n",
    "    def front = {\n",
    "        val f0 = Cube(outerWidth, frontThickness, frontHeight)\n",
    "        // remove material to go over the pillar's knee\n",
    "        val knee = pillarInnerspace + Pillar.width * 2 + 10\n",
    "        val f1 = f0 - Cube(knee, frontThickness, Pillar.kneeHeight + 5).moveX((outerWidth - knee) / 2)\n",
    "        // holes to attach to side\n",
    "        val f2 = f1 -- frontHolesPositions.map( z => frontBackScrew.move(sideThickness/2, 0, z) +\n",
    "                                                     frontBackScrew.move(outerWidth - sideThickness/2, 0, z))\n",
    "        // holes to attach the cantilever\n",
    "        val s = Cylinder(cantileverHoles, frontThickness).rotateX(-90)\n",
    "        val f3 = f2 -- cantileverHolesPositions.map{ case (x,z) => s.move(outerWidth/2+x, 0, frontHeight - cantileverHeight + z) }\n",
    "        f3\n",
    "    }\n",
    "    \n",
    "    def spindlePlate = SpindlePlate.model.rotateX(90).moveY(SpindlePlate.height)\n",
    "    \n",
    "    def model = {\n",
    "        val sideAndGuides = {\n",
    "            val g = LinearGuide.model.rotateY(-90).rotateZ(180).moveX(sideThickness)\n",
    "            val s = side + g.move(0, guideDepth, lowerGuideHeight) + g.move(0, guideDepth, upperGuideHeight)\n",
    "            s.move(-outerWidth/2, 0, 0)\n",
    "        }\n",
    "        val spindle = spindlePlate + SpindleClamp.model.rotateZ(180).moveX(SpindleClamp.width)\n",
    "        sideAndGuides +\n",
    "        sideAndGuides.mirror(1,0,0) +\n",
    "        front.move(-outerWidth/2, -frontThickness, 0) +\n",
    "        back.move(-outerWidth/2, sideDepth, height - backHeight - backHeightOffset) +\n",
    "        cantilever.move(0, -cantileverDepth -frontThickness, height - cantileverHeight) +\n",
    "        spindle.move(-cantileverWidth/2, -cantileverDepth - frontThickness - sideThickness, height - (cantileverHeight + SpindleClamp.height))\n",
    "    }\n",
    "    \n",
    "    def info = {\n",
    "        s\"\"\"|Carriage (assembly):\n",
    "            |  side (2x)\n",
    "            |    width = $sideThickness\n",
    "            |    depth = $sideDepth\n",
    "            |    height = $height\n",
    "            |  front (1x)\n",
    "            |    width = $outerWidth\n",
    "            |    depth = $frontThickness\n",
    "            |    height = $frontHeight\n",
    "            |  back (1x)\n",
    "            |    width = $outerWidth\n",
    "            |    depth = $backThickness\n",
    "            |    height = $backHeight\n",
    "            |  cantilever (assembly)\n",
    "            |    side (2x)\n",
    "            |      width = $sideThickness\n",
    "            |      depth = $cantileverDepth\n",
    "            |      height = $cantileverHeight\n",
    "            |    top (1x)\n",
    "            |      width = $cantileverWidth\n",
    "            |      depth = ${cantileverDepth + frontThickness * 2}\n",
    "            |      height = $backThickness\n",
    "            |  spindle plate (1x)\n",
    "            |    width = $cantileverWidth\n",
    "            |    depth = $sideThickness\n",
    "            |    height = ${cantileverHeight + SpindleClamp.height}\"\"\".stripMargin\n",
    "    }\n",
    "}\n",
    "//TODO splindle plate should be thicker and have countersunk screw ? or go for some kind of angle brackets / side bar ?\n",
    "//TODO countersunk on the front plate\n",
    "//TODO save some material on the front plate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6a2b12c3-a1ff-4a0e-a363-a1ebf1db6844",
   "metadata": {},
   "outputs": [],
   "source": [
    "val mesh = OpenSCAD(Carriage.cantilever)\n",
    "Viewer(mesh)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "da254c87-0bf3-40bc-aba4-dfa6578b353e",
   "metadata": {},
   "source": [
    "### Together"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "028a9bc5-a09a-4497-8119-1f2a7b753196",
   "metadata": {},
   "outputs": [],
   "source": [
    "val base = Base.model.rotateY(180).move(Base.width, 0, Base.height)\n",
    "val column = {\n",
    "    val pr = Pillar.model + LinearRail.rail(Pillar.railLength).rotateY(-90).moveY(Pillar.depth/2)\n",
    "    val p = pr.move(-pillarInnerspace / 2 - Pillar.width, 0, 0)\n",
    "    p + p.mirror(1,0,0) +\n",
    "    FrontPlate.model.move(-FrontPlate.width/2, 0, 0) +\n",
    "    BallScrew.model(FrontPlate.ballScrewLength).rotateY(-90).rotateZ(-90).moveZ(FrontPlate.height - 10 - FrontPlate.ballScrewLength)\n",
    "}\n",
    "val carriage = Carriage.model\n",
    "val table = Table.placeholder()\n",
    "val cnc = {\n",
    "    base.move(-Base.width / 2, 0 , -Base.height) +\n",
    "    column.move(0, Base.depth - Pillar.depth, 0) +\n",
    "    carriage.move(0, Base.depth - Carriage.sideDepth + Carriage.frontBackClearance, 200) +\n",
    "    table.move(0,100,0)\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ddb7292e-8af8-4019-9e56-fdf834e3b449",
   "metadata": {},
   "outputs": [],
   "source": [
    "val mesh = OpenSCAD(cnc)\n",
    "Viewer(mesh)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3edb821c-27d8-49d0-9fe2-446c59f60a02",
   "metadata": {},
   "outputs": [],
   "source": [
    "OpenSCAD.toSTL(cnc, \"cnc.stl\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c2bd225c-8df0-407c-8232-180713c0385a",
   "metadata": {},
   "source": [
    "### List of parts"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3e787aea-6e5f-40ee-8689-e527b7cd8704",
   "metadata": {},
   "outputs": [],
   "source": [
    "println(Base.info)\n",
    "println(Pillar.info)\n",
    "println(FrontPlate.info)\n",
    "println(Carriage.info)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "41b12f22-04cb-4415-b467-a3588dd60ce5",
   "metadata": {},
   "source": [
    "## Gearbox to hold the motor and handwheel\n",
    "\n",
    "For the gear, we will use some files from Thingiverse.\n",
    "The gears are CC-BY-SA by GeneralRulofDumb, see https://www.thingiverse.com/thing:10955.\n",
    "\n",
    "The gears (original scale) are offset `12.1 mm` from the intersection of the two rotation axes."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "04b2c735-fe27-4f03-ad64-0273901e786b",
   "metadata": {},
   "outputs": [],
   "source": [
    "// get the bevel gear\n",
    "import java.nio.file.{Paths, Files}\n",
    "import java.net.{HttpURLConnection,URL}\n",
    "\n",
    "val gearLeft = FromFile(\"gear_hypoid_left.stl\")\n",
    "val gearRight = FromFile(\"gear_hypoid_right.stl\")\n",
    "\n",
    "val gearLeftURL = \"https://cdn.thingiverse.com/assets/08/c0/2b/0d/90/gear_hypoid_left.stl\"\n",
    "val gearRightURL = \"https://cdn.thingiverse.com/assets/e8/ab/bd/72/48/gear_hypoid_right.stl\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b73cc31b-3dc5-44a5-8e0b-c70817864fbb",
   "metadata": {},
   "outputs": [],
   "source": [
    "def getFile(address: String, file: String) = {\n",
    "    if (!Files.exists(Paths.get(file))) {\n",
    "        val url = new URL(address)\n",
    "        val connection = url.openConnection().asInstanceOf[HttpURLConnection]\n",
    "        connection.connect()\n",
    "        try {\n",
    "            val code = connection.getResponseCode\n",
    "            if (code != 200) {\n",
    "                println(\"error \" + code)\n",
    "            } else {\n",
    "                url #> new File(file) !!\n",
    "            }\n",
    "        } finally {\n",
    "            connection.close()\n",
    "        }\n",
    "    }\n",
    "}\n",
    "\n",
    "getFile(gearLeftURL, gearLeft)\n",
    "getFile(gearRightURL, gearRight)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "883cad4c-e994-4bb1-9701-679dd4b4c6b9",
   "metadata": {},
   "source": [
    "This part is designed to be 3D printed rather than milled.\n",
    "\n",
    "The faceplate for a nema motor is\n",
    "- `56.4 mm` wide\n",
    "- holes are `47.14 mm` apart\n",
    "- center flange is `38.1mm` in diameter"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f49a47e8-39e6-41d6-b04a-17fee2d4f63d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Scala",
   "language": "scala",
   "name": "scala"
  },
  "language_info": {
   "codemirror_mode": "text/x-scala",
   "file_extension": ".sc",
   "mimetype": "text/x-scala",
   "name": "scala",
   "nbconvert_exporter": "script",
   "version": "2.13.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
